### ISSUE TITLE
[meta] Tracker for container insight arm64 support

### ISSUE THREAD

**Issue by pingleig** [aws/amazon-cloudwatch-agent#114]
This is a tracker to direct discussion of existing issues into one place. There is no detailed timeline (yet). Please leave feedback if you are planning to use it or have concern for breaking changes (if any).

## Background

[EKS Graviton support is GA](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-support-for-arm-based-instances-powered-by-aws-graviton-now-generally-available/) and cloudwatch-agent already has an arm64 build (not containerized). Fludentd has [arm64 dameonset build](https://github.com/fluent/fluentd-kubernetes-daemonset#arm64-images).

## Related Issues

 - [Arm64 support, including multi-arch amazon/cloudwatch-agent](https://github.com/aws-samples/amazon-cloudwatch-container-insights/issues/35)
- [EKS: ARM64 support for "Container Insights"](https://github.com/aws/containers-roadmap/issues/1023)
 - [Added NodeSelector to prevent it from running on windows Nodes](https://github.com/aws-samples/amazon-cloudwatch-container-insights/pull/41) We are likely to update label selector because fluentd daemonset does not use multi arch image.

## Not related issues

-  [#104 Raspberry pi](https://github.com/aws/amazon-cloudwatch-agent/issues/104) we are not creating new `arm` build

## Design

- Provide a multi arch image on dockerhub like [xray-dameon](https://hub.docker.com/r/amazon/aws-xray-daemon/tags)
  - Existing manifest should still work in theory i.e. pull amd64 on amd64 host, haven't tested it with dockerhub though.
- Provide new repo/tag that contains `arm64` `amd64` for people using registry/runtime that does not support multi arch image NOTE:  [Amazon ECR supports it](https://aws.amazon.com/blogs/containers/introducing-multi-architecture-container-images-for-amazon-ecr/)

## TODO

- [x] ~~provide full snippet for workaround~~
- [x] official arm64 image
- [x] ~~Update related manifest in~~ We recommend users to use fluent-bit which has a multi-arch image, for fluentd users need update the image tag manually since the official daemonset image is x86 only.
   - [x] [this repo](https://github.com/aws/amazon-cloudwatch-agent/tree/master/amazon-cloudwatch-container-insights)
   - [x] [example](https://github.com/aws-samples/amazon-cloudwatch-container-insights) 
   - [x]  [doc](https://github.com/awsdocs/amazon-cloudwatch-user-guide)

## Workaround

It is possible to build arm image by yourself from [official arm64 packages](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html). Running [docker buildx](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) or creating an ARM instance on ec2 as a builder box should both work.

You need to modify example manifests to make sure you are

- Using arm64 version of fluentd image
- Using node selector `arch=arm64` if your eks cluster is mixing amd64 and arm64 node groups. Even if you build a mult-arch image for cloudwatch-agent,  fluentd is still specifying arch using image tag.

**Comment by pingleig** [comment]
The arm64 image is out on [dockerhub](https://hub.docker.com/r/amazon/cloudwatch-agent/tags?page=1&ordering=last_updated) and [public ECR](https://gallery.ecr.aws/cloudwatch-agent/cloudwatch-agent)

**Comment by pingleig** [comment]
The public doc is updated (somehow it seems it is out of sync w/ the github repo). If you are using the agent only, there is no need to change anything, the docker image is multi arch so it works out of box. If you use fluentd, you need to update the image tag to match the arch See [install fluentd](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html#ContainerInsights-install-FluentD). The recommended approach is using fluent-bit.

Related links

- [Amazon CloudWatch Container Insights now available on AWS Graviton2](https://aws.amazon.com/about-aws/whats-new/2021/01/amazon-cloudwatch-container-insights-available-aws-graviton2/)
